package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import main.Common;
import static main.Common.CURRENT_COACH;
import main.KabumbuFootballLeage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Victor
 */
public class CoachRegestrationFormConfirmation extends javax.swing.JFrame {

    /**
     * Creates new form CoachRegestrationFormConfirmation
     */
    public CoachRegestrationFormConfirmation() {
        initComponents();
    }

    public void populate() {
        enteredFirstName.setText(Common.CURRENT_COACH.getfName());
        enteredLastName.setText(Common.CURRENT_COACH.getlName());
        enteredDateOfBirth.setText(Common.CURRENT_COACH.getDateOfBirth()+ "");
        enteredSchoolId.setText(Common.CURRENT_COACH.getSchoolId() + "");
        enteredNationalId.setText(Common.CURRENT_COACH.getIdNum() + "");
        enteredPhoneNumber.setText(Common.CURRENT_COACH.getPhoneNum() + "");
        enteredEmailAddress.setText(Common.CURRENT_COACH.getEmailAdd());
        enteredSchoolCoaching.setText(Common.CURRENT_COACH.getSchCoaching());
        yesOrNoSelected.setText(Common.CURRENT_COACH.getMedicalIssue());
        enteredExplanationOfMedicalIssue.setText(Common.CURRENT_COACH.getExplanationMedical());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoachRegestationConfirmation = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        coachFirstName = new javax.swing.JLabel();
        enteredFirstName = new javax.swing.JLabel();
        coachLastName = new javax.swing.JLabel();
        enteredLastName = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        nationalId = new javax.swing.JLabel();
        enteredNationalId = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        enteredPhoneNumber = new javax.swing.JLabel();
        emailAddress = new javax.swing.JLabel();
        enteredEmailAddress = new javax.swing.JLabel();
        SchoolCoaching = new javax.swing.JLabel();
        enteredSchoolCoaching = new javax.swing.JLabel();
        allergiesOrMedicalIssues = new javax.swing.JLabel();
        yesOrNoSelected = new javax.swing.JLabel();
        explanationOfAllergyAndMedication = new javax.swing.JLabel();
        enteredExplanationOfMedicalIssue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        enteredSchoolId = new javax.swing.JLabel();
        enteredDateOfBirth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CoachRegestationConfirmation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CoachRegestationConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoachRegestationConfirmation.setText("Coach Regestration Form");

        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ConfirmBtn.setText("Confirm");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        coachFirstName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        coachFirstName.setText("First Name :");

        coachLastName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        coachLastName.setText("Last Name:");

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dateOfBirth.setText("Date of Birth:");

        nationalId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nationalId.setText("National Id :");

        phoneNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        phoneNumber.setText("Phone Number :");

        emailAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emailAddress.setText("Email Address :");

        SchoolCoaching.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SchoolCoaching.setText("School Coaching :");

        allergiesOrMedicalIssues.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        allergiesOrMedicalIssues.setText("Do you have any allergies or medical isssues ?");

        explanationOfAllergyAndMedication.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        explanationOfAllergyAndMedication.setText("If yes please explain your allergie or medical issue bellow ");

        enteredExplanationOfMedicalIssue.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("School ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoachRegestationConfirmation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coachFirstName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enteredSchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enteredFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(coachLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enteredLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(explanationOfAllergyAndMedication)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allergiesOrMedicalIssues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesOrNoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(enteredExplanationOfMedicalIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enteredSchoolId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nationalId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enteredNationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enteredPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enteredEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enteredDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoachRegestationConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coachLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enteredLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coachFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enteredFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(enteredSchoolId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredNationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredSchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yesOrNoSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergiesOrMedicalIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(explanationOfAllergyAndMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteredExplanationOfMedicalIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO coach (firstName, lastName, schoolid, dateOfBirth, nationalId, phoneNumber, email, schoolCoaching, medicalIssue, explanation)"
                + "VALUES (?,?,?,?,?,?,?,?,?,?)";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kambumbufootballleagemanagementsystem", "root", "");
                PreparedStatement pstmt = conn.prepareStatement(sql)) {            
            pstmt.setString(1, CURRENT_COACH.getfName());
            pstmt.setString(2, CURRENT_COACH.getlName());
            pstmt.setInt(3, CURRENT_COACH.getSchoolId());
            pstmt.setString(4, CURRENT_COACH.getDateOfBirth()+ "");
            pstmt.setString(5, CURRENT_COACH.getIdNum() + "");
            pstmt.setString(6, CURRENT_COACH.getPhoneNum() + "");
            pstmt.setString(7, CURRENT_COACH.getEmailAdd());
            pstmt.setString(8, CURRENT_COACH.getSchCoaching());
            pstmt.setString(9, CURRENT_COACH.getMedicalIssue());
            pstmt.setString(10, CURRENT_COACH.getExplanationMedical());    
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully Regestered!");
            setVisible(false);
            KabumbuFootballLeage.crhp.populateCoach();
            KabumbuFootballLeage.crhp.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(KabumbuFootballLeage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KabumbuFootballLeage.crf.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationFormConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationFormConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationFormConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationFormConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachRegestrationFormConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoachRegestationConfirmation;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JLabel SchoolCoaching;
    private javax.swing.JLabel allergiesOrMedicalIssues;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel coachFirstName;
    private javax.swing.JLabel coachLastName;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JLabel emailAddress;
    private javax.swing.JLabel enteredDateOfBirth;
    private javax.swing.JLabel enteredEmailAddress;
    private javax.swing.JLabel enteredExplanationOfMedicalIssue;
    private javax.swing.JLabel enteredFirstName;
    private javax.swing.JLabel enteredLastName;
    private javax.swing.JLabel enteredNationalId;
    private javax.swing.JLabel enteredPhoneNumber;
    private javax.swing.JLabel enteredSchoolCoaching;
    private javax.swing.JLabel enteredSchoolId;
    private javax.swing.JLabel explanationOfAllergyAndMedication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nationalId;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel yesOrNoSelected;
    // End of variables declaration//GEN-END:variables
}
