package view;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Common;
import main.KabumbuFootballLeage;
import model.Coach;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Victor
 */
public class CoachRegestrationForm extends javax.swing.JFrame {

    /**
     * Creates new form CoachRegestrationForm
     */
    public CoachRegestrationForm() {
        initComponents();
        String sql = "SELECT schoolname, schoolid FROM schools;";
        try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kambumbufootballleagemanagementsystem", "root", "");
                Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()) {
                String schoolN = rs.getString("schoolname");
                int schoolID = rs.getInt("schoolid");
                jComboBoxSchoolCoaching.addItem(schoolN);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CoachRegestrationForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupYesOrNo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        firstNameOfCoach = new javax.swing.JLabel();
        jTextFieldFirstNameCoach = new javax.swing.JTextField();
        lastNameOfCoach = new javax.swing.JLabel();
        jTextFieldLastNameCoach = new javax.swing.JTextField();
        jButtonDoneCoachRegestration = new javax.swing.JButton();
        jButtonCancelCoachRegestration = new javax.swing.JButton();
        DateOfBirth = new javax.swing.JLabel();
        NationalId = new javax.swing.JLabel();
        jTextFieldNationalId = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        emaiAddress = new javax.swing.JLabel();
        jTextFieldEmailAddress = new javax.swing.JTextField();
        schoolCoaching = new javax.swing.JLabel();
        jComboBoxSchoolCoaching = new javax.swing.JComboBox<>();
        allergiesOrMedicalIssues = new javax.swing.JLabel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        eplain = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        schoolIdTf = new javax.swing.JTextField();
        dateOfBirthTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coach Regesrtration Form");

        firstNameOfCoach.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        firstNameOfCoach.setText("First Name");

        lastNameOfCoach.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lastNameOfCoach.setText("Last Name");

        jButtonDoneCoachRegestration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonDoneCoachRegestration.setText("Done");
        jButtonDoneCoachRegestration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneCoachRegestrationActionPerformed(evt);
            }
        });

        jButtonCancelCoachRegestration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelCoachRegestration.setText("Cancel");
        jButtonCancelCoachRegestration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelCoachRegestrationActionPerformed(evt);
            }
        });

        DateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DateOfBirth.setText("Date of Birth");

        NationalId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NationalId.setText("National Id");

        PhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PhoneNumber.setText("Phone Number");

        emaiAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emaiAddress.setText("Email Address");

        schoolCoaching.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        schoolCoaching.setText("School Coaching");

        jComboBoxSchoolCoaching.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select school" }));
        jComboBoxSchoolCoaching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSchoolCoachingActionPerformed(evt);
            }
        });

        allergiesOrMedicalIssues.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        allergiesOrMedicalIssues.setText("Do you have any allergies or any medical issues ?");

        buttonGroupYesOrNo.add(jRadioButtonYes);
        jRadioButtonYes.setText("Yes");

        buttonGroupYesOrNo.add(jRadioButtonNo);
        jRadioButtonNo.setText("No");

        eplain.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        eplain.setText("If yes please explain your allergy or medical condition below");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("School Id");

        dateOfBirthTf.setText("dd/mm/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(firstNameOfCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextFieldFirstNameCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastNameOfCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLastNameCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(allergiesOrMedicalIssues, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(schoolCoaching, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                    .addComponent(emaiAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(PhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(DateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(NationalId))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxSchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(dateOfBirthTf, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(schoolIdTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldNationalId, javax.swing.GroupLayout.Alignment.LEADING)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jRadioButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelCoachRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDoneCoachRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eplain, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lastNameOfCoach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFirstNameCoach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(firstNameOfCoach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLastNameCoach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(dateOfBirthTf))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(schoolIdTf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaiAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSchoolCoaching, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allergiesOrMedicalIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonYes)
                    .addComponent(jRadioButtonNo))
                .addGap(11, 11, 11)
                .addComponent(eplain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelCoachRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDoneCoachRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDoneCoachRegestrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneCoachRegestrationActionPerformed
        // TODO add your handling code here:
        String fName = jTextFieldFirstNameCoach.getText();
        String lName = jTextFieldLastNameCoach.getText();
        java.sql.Date dateOfBirth = null;
        try{
            final DateFormat format = new SimpleDateFormat("dd/mm/yy");
            java.util.Date date = format.parse(dateOfBirthTf.getText()); 
            dateOfBirth = new java.sql.Date(date.getTime());
        }catch (ParseException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog (this, "Please input date of birth correctly");
            return;
        }
        int schoolId = Integer.parseInt(schoolIdTf.getText());
        int idNum = Integer.parseInt(jTextFieldNationalId.getText());
        int phoneNum = Integer.parseInt(jTextFieldPhoneNumber.getText());
        String emailAdd = jTextFieldEmailAddress.getText();
        String schCoaching = jComboBoxSchoolCoaching.getSelectedItem().toString();
        String medicalIssues;
        if (jRadioButtonYes.isSelected()) {
            medicalIssues = "YES";
        } else {
            medicalIssues = "NO";
        }

        String explanationMedical = jTextArea1.getText();

        //int id, String fName, String lName, int day, int month, int year, int idNum, int phoneNum, String emailAdd, String schCoaching, String medicalIssue, String explanationMedical
        Common.CURRENT_COACH = new Coach(0, fName, lName, dateOfBirth, schoolId, idNum, phoneNum, emailAdd, schCoaching, medicalIssues, explanationMedical);

        setVisible(false);
        KabumbuFootballLeage.crfc.populate();
        KabumbuFootballLeage.crfc.setVisible(true);

    }//GEN-LAST:event_jButtonDoneCoachRegestrationActionPerformed

    private void jButtonCancelCoachRegestrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelCoachRegestrationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KabumbuFootballLeage.crhp.setVisible(true);
    }//GEN-LAST:event_jButtonCancelCoachRegestrationActionPerformed

    private void jComboBoxSchoolCoachingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSchoolCoachingActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxSchoolCoachingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachRegestrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachRegestrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirth;
    private javax.swing.JLabel NationalId;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel allergiesOrMedicalIssues;
    private javax.swing.ButtonGroup buttonGroupYesOrNo;
    private javax.swing.JTextField dateOfBirthTf;
    private javax.swing.JLabel emaiAddress;
    private javax.swing.JLabel eplain;
    private javax.swing.JLabel firstNameOfCoach;
    private javax.swing.JButton jButtonCancelCoachRegestration;
    private javax.swing.JButton jButtonDoneCoachRegestration;
    private javax.swing.JComboBox<String> jComboBoxSchoolCoaching;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldEmailAddress;
    private javax.swing.JTextField jTextFieldFirstNameCoach;
    private javax.swing.JTextField jTextFieldLastNameCoach;
    private javax.swing.JTextField jTextFieldNationalId;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JLabel lastNameOfCoach;
    private javax.swing.JLabel schoolCoaching;
    private javax.swing.JTextField schoolIdTf;
    // End of variables declaration//GEN-END:variables
}
