
package view;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Common;
import main.KabumbuFootballLeage;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

/**
 *
 * @author Victor
 */
public class RefereeRegestrationConfirmatiom extends javax.swing.JFrame {

    /**
     * Creates new form RefereeRegestrationConfirmatiom
     */
    public RefereeRegestrationConfirmatiom() {
        initComponents();
    }
    
    public void populate(){
        enteredFirstName.setText(Common.CURRENT_REFEREE.getfName());
        enteredLastName.setText(Common.CURRENT_REFEREE.getlName());
        enteredDateOfBirth.setText(Common.CURRENT_REFEREE.getDateOfBirth()+"");
        enteredSchoolId.setText(Common.CURRENT_REFEREE.getSchoolId()+"");
        enteredNationalIdNumber.setText(Common.CURRENT_REFEREE.getNationalId() +"");
        enteredPhoneNumber.setText(Common.CURRENT_REFEREE.getPhoneNumber() +"");
        enteredEmailAddress.setText(Common.CURRENT_REFEREE.getEmailAddress());
        selectedSex.setText(Common.CURRENT_REFEREE.getSex());
        enteredYearbeganRefereeing.setText(Common.CURRENT_REFEREE.getYearBeganReferee() +"");
        selectedSchoolTeam.setText(Common.CURRENT_REFEREE.getSchoolTeam());
        selectedYesOrNo.setText(Common.CURRENT_REFEREE.getWillingInterCountyGames());
        selectedGrades.setText(Common.CURRENT_REFEREE.getRefereeGrade());
        selectedTimeForSecondLevelGames.setText(Common.CURRENT_REFEREE.getAvailableSecondarylevel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refereeRegestration = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        enteredFirstName = new javax.swing.JLabel();
        secondName = new javax.swing.JLabel();
        enteredLastName = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        nationalId = new javax.swing.JLabel();
        enteredNationalIdNumber = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        enteredPhoneNumber = new javax.swing.JLabel();
        emailAddress = new javax.swing.JLabel();
        enteredEmailAddress = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        selectedSex = new javax.swing.JLabel();
        beginRefering = new javax.swing.JLabel();
        yearVeganRefereeing = new javax.swing.JLabel();
        enteredYearbeganRefereeing = new javax.swing.JLabel();
        schoolTeam = new javax.swing.JLabel();
        selectedSchoolTeam = new javax.swing.JLabel();
        willingToRefereeIntercountyGames = new javax.swing.JLabel();
        selectedYesOrNo = new javax.swing.JLabel();
        gradesToReferee = new javax.swing.JLabel();
        selectedGrades = new javax.swing.JLabel();
        availabilitySecondLevelGames = new javax.swing.JLabel();
        selectedTimeForSecondLevelGames = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enteredSchoolId = new javax.swing.JLabel();
        enteredDateOfBirth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refereeRegestration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refereeRegestration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refereeRegestration.setText("Referee Regestration");

        firstName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        firstName.setText("First Name :");

        secondName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        secondName.setText("Last Name :");

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dateOfBirth.setText("Date of Birth:");

        nationalId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nationalId.setText("National ID Number :");

        phoneNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        phoneNumber.setText("Phone Number :");

        emailAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emailAddress.setText("Email Address :");

        sex.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sex.setText("Sex :");

        beginRefering.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        beginRefering.setText("Since when did you begin being a referee ?");

        yearVeganRefereeing.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        yearVeganRefereeing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearVeganRefereeing.setText("Year :");

        schoolTeam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        schoolTeam.setText("School Team :");

        willingToRefereeIntercountyGames.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        willingToRefereeIntercountyGames.setText("Are you willing to referree inter-county games ?");

        gradesToReferee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gradesToReferee.setText("If yes, which grades do you referee ? (tick all that apply) ");

        availabilitySecondLevelGames.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        availabilitySecondLevelGames.setText("Are you available to referee second-level games ? (Daytime)");

        confirmBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("School ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refereeRegestration, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nationalId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enteredFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(secondName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(enteredLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(enteredNationalIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(schoolTeam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selectedSchoolTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(beginRefering)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(yearVeganRefereeing, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enteredYearbeganRefereeing, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(willingToRefereeIntercountyGames)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selectedYesOrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(gradesToReferee)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selectedGrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(availabilitySecondLevelGames)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(selectedTimeForSecondLevelGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enteredSchoolId, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(phoneNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enteredPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(emailAddress)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enteredEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sex)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selectedSex, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(enteredDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refereeRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enteredFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enteredLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(enteredDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(enteredSchoolId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredNationalIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedSex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginRefering, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearVeganRefereeing, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredYearbeganRefereeing, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedSchoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(willingToRefereeIntercountyGames, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedYesOrNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradesToReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availabilitySecondLevelGames, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedTimeForSecondLevelGames, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KabumbuFootballLeage.rrf.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO referees (firstname, lastname, dateOfBirth, schoolid, nationalid,phoneNumber, emailAddress, sex, yearBeganReferee, schoolTeam, willingToRefereeInterCountyGames, gradeOfReferee, availableForSecondLevelGames)"
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kambumbufootballleagemanagementsystem", "root", "");
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, Common.CURRENT_REFEREE.getfName());
            pstmt.setString(2, Common.CURRENT_REFEREE.getlName());
            pstmt.setString(3, Common.CURRENT_REFEREE.getDateOfBirth() + "");
            pstmt.setString(4, Common.CURRENT_REFEREE.getSchoolId() + "");
            pstmt.setString(5, Common.CURRENT_REFEREE.getNationalId() + "");
            pstmt.setString(6, Common.CURRENT_REFEREE.getPhoneNumber() + "");
            pstmt.setString(7, Common.CURRENT_REFEREE.getEmailAddress());
            pstmt.setString(8, Common.CURRENT_REFEREE.getSex());
            pstmt.setString(9, Common.CURRENT_REFEREE.getYearBeganReferee()+"");
            pstmt.setString(10, Common.CURRENT_REFEREE.getSchoolTeam());
            pstmt.setString(11, Common.CURRENT_REFEREE.getWillingInterCountyGames());
            pstmt.setString(12, Common.CURRENT_REFEREE.getRefereeGrade());
            pstmt.setString(13, Common.CURRENT_REFEREE.getAvailableSecondarylevel());
            
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully Registered!");
            setVisible(false);
            KabumbuFootballLeage.rrhp.populateReferee();
            KabumbuFootballLeage.rrhp.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(KabumbuFootballLeage.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error saving your credentials", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestrationConfirmatiom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestrationConfirmatiom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestrationConfirmatiom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestrationConfirmatiom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RefereeRegestrationConfirmatiom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilitySecondLevelGames;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel beginRefering;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JLabel emailAddress;
    private javax.swing.JLabel enteredDateOfBirth;
    private javax.swing.JLabel enteredEmailAddress;
    private javax.swing.JLabel enteredFirstName;
    private javax.swing.JLabel enteredLastName;
    private javax.swing.JLabel enteredNationalIdNumber;
    private javax.swing.JLabel enteredPhoneNumber;
    private javax.swing.JLabel enteredSchoolId;
    private javax.swing.JLabel enteredYearbeganRefereeing;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel gradesToReferee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nationalId;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel refereeRegestration;
    private javax.swing.JLabel schoolTeam;
    private javax.swing.JLabel secondName;
    private javax.swing.JLabel selectedGrades;
    private javax.swing.JLabel selectedSchoolTeam;
    private javax.swing.JLabel selectedSex;
    private javax.swing.JLabel selectedTimeForSecondLevelGames;
    private javax.swing.JLabel selectedYesOrNo;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel willingToRefereeIntercountyGames;
    private javax.swing.JLabel yearVeganRefereeing;
    // End of variables declaration//GEN-END:variables
}
