package view;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Common;
import main.KabumbuFootballLeage;
import model.Referee;

// Referee rgestration form

/**
 *
 * @author Victor
 */
public class RefereeRegestration extends javax.swing.JFrame {

    /**
     * Creates new form RefereeRegestration
     */
    public RefereeRegestration() {
        initComponents();
        
        String sql = "SELECT schoolname, schoolid FROM schools;";
        try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kambumbufootballleagemanagementsystem", "root", "");
                Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()) {
                String schoolN = rs.getString("schoolname");
                int schoolID = rs.getInt("schoolid");
                jComboBoxSchoolTeam.addItem(schoolN);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CoachRegestrationForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFemaleOrMale = new javax.swing.ButtonGroup();
        buttonGroupYesOrNo = new javax.swing.ButtonGroup();
        buttonGroupYesOrNoJuvenile = new javax.swing.ButtonGroup();
        buttonGroupYesOrNoMinor = new javax.swing.ButtonGroup();
        buttonGroupYesOrNoSeniorGrade = new javax.swing.ButtonGroup();
        buttonGroupSecondLevel = new javax.swing.ButtonGroup();
        refereeRegestrationForm = new javax.swing.JLabel();
        refereeFirstName = new javax.swing.JLabel();
        jTextRefereeFirstName = new javax.swing.JTextField();
        refereeLastName = new javax.swing.JLabel();
        jTextRefereeLastName = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        refereePhoneNumber = new javax.swing.JLabel();
        jTextRefereePhoneNumber = new javax.swing.JTextField();
        refereeEmailAddress = new javax.swing.JLabel();
        jTextRefereeEmailAddress = new javax.swing.JTextField();
        sex = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        schoolTeam = new javax.swing.JLabel();
        jComboBoxSchoolTeam = new javax.swing.JComboBox<>();
        areYouWillingToReferee = new javax.swing.JLabel();
        jRadioButtonYesWilling = new javax.swing.JRadioButton();
        jRadioButtonNotWilling = new javax.swing.JRadioButton();
        degreeToReferee = new javax.swing.JLabel();
        juvenileGrade = new javax.swing.JLabel();
        jCheckBoxYesJuvenile = new javax.swing.JCheckBox();
        minorGrade = new javax.swing.JLabel();
        jCheckBoxYesMinor = new javax.swing.JCheckBox();
        seniorGrade = new javax.swing.JLabel();
        jCheckBoxYesSeniorGrade = new javax.swing.JCheckBox();
        availabilityForSecondLevelGames = new javax.swing.JLabel();
        beginReferee = new javax.swing.JLabel();
        jSpinnerBeginRefereeYear = new javax.swing.JSpinner();
        beginRefereeYear = new javax.swing.JLabel();
        jCheckBoxAllTimeAvailableSecondLevel = new javax.swing.JCheckBox();
        jCheckBoxWeekdayAvailableSecondLevel = new javax.swing.JCheckBox();
        jCheckBoxWeekendAvailableSecondLevel = new javax.swing.JCheckBox();
        jButtonDoneRegesteringReferee = new javax.swing.JButton();
        jButtonCancelRefereeRegestration = new javax.swing.JButton();
        NationalId = new javax.swing.JLabel();
        jTextFieldNationalId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        schoolIdTf = new javax.swing.JTextField();
        dateOfBirthTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refereeRegestrationForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refereeRegestrationForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refereeRegestrationForm.setText("Referee Registration ");

        refereeFirstName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refereeFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refereeFirstName.setText("First Name");

        jTextRefereeFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRefereeFirstNameActionPerformed(evt);
            }
        });

        refereeLastName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refereeLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refereeLastName.setText("Last Name");

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateOfBirth.setText("Date of Birth");

        refereePhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refereePhoneNumber.setText("Phone Number");

        jTextRefereePhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRefereePhoneNumberActionPerformed(evt);
            }
        });

        refereeEmailAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refereeEmailAddress.setText("Email Address");

        sex.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sex.setText("Sex");

        buttonGroupFemaleOrMale.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupFemaleOrMale.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");

        schoolTeam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        schoolTeam.setText("School Team");

        jComboBoxSchoolTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select school" }));
        jComboBoxSchoolTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSchoolTeamActionPerformed(evt);
            }
        });

        areYouWillingToReferee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        areYouWillingToReferee.setText("Are you willing to referree inter-county games ?");

        buttonGroupYesOrNo.add(jRadioButtonYesWilling);
        jRadioButtonYesWilling.setText("Yes");

        buttonGroupYesOrNo.add(jRadioButtonNotWilling);
        jRadioButtonNotWilling.setText("No");

        degreeToReferee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        degreeToReferee.setText("If yes, which grades do you referee ? (tick all that apply) ");

        juvenileGrade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        juvenileGrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juvenileGrade.setText("Juvenile");

        buttonGroupYesOrNoJuvenile.add(jCheckBoxYesJuvenile);
        jCheckBoxYesJuvenile.setText("Yes");
        jCheckBoxYesJuvenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxYesJuvenileActionPerformed(evt);
            }
        });

        minorGrade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        minorGrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minorGrade.setText("Minor");

        buttonGroupYesOrNoJuvenile.add(jCheckBoxYesMinor);
        jCheckBoxYesMinor.setText("Yes");

        seniorGrade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        seniorGrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seniorGrade.setText("Senior");

        buttonGroupYesOrNoJuvenile.add(jCheckBoxYesSeniorGrade);
        jCheckBoxYesSeniorGrade.setText("Yes");

        availabilityForSecondLevelGames.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        availabilityForSecondLevelGames.setText("Are you available to referee second-level games ? (Daytime)");

        beginReferee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        beginReferee.setText("Since when did you begin being a referee ?");

        beginRefereeYear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        beginRefereeYear.setText("Year");

        buttonGroupSecondLevel.add(jCheckBoxAllTimeAvailableSecondLevel);
        jCheckBoxAllTimeAvailableSecondLevel.setText("All Time");

        buttonGroupSecondLevel.add(jCheckBoxWeekdayAvailableSecondLevel);
        jCheckBoxWeekdayAvailableSecondLevel.setText("Week-days");

        buttonGroupSecondLevel.add(jCheckBoxWeekendAvailableSecondLevel);
        jCheckBoxWeekendAvailableSecondLevel.setText("Weekend");

        jButtonDoneRegesteringReferee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonDoneRegesteringReferee.setText("Done");
        jButtonDoneRegesteringReferee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneRegesteringRefereeActionPerformed(evt);
            }
        });

        jButtonCancelRefereeRegestration.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelRefereeRegestration.setText("Cancel");
        jButtonCancelRefereeRegestration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelRefereeRegestrationActionPerformed(evt);
            }
        });

        NationalId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NationalId.setText("National Id Number");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("School id");

        dateOfBirthTf.setText("dd/mm/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelRefereeRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDoneRegesteringReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seniorGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minorGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(juvenileGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxYesJuvenile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBoxYesSeniorGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(jCheckBoxYesMinor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refereeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextRefereeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refereeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextRefereeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxWeekendAvailableSecondLevel)
                                    .addComponent(jCheckBoxWeekdayAvailableSecondLevel)
                                    .addComponent(jCheckBoxAllTimeAvailableSecondLevel)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(refereePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextRefereePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(NationalId)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNationalId, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                        .addComponent(schoolIdTf)
                                        .addComponent(dateOfBirthTf))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(refereeRegestrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(areYouWillingToReferee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(degreeToReferee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(availabilityForSecondLevelGames, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jRadioButtonYesWilling, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNotWilling, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(schoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSchoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(refereeEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFemale))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextRefereeEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(beginReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beginRefereeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBeginRefereeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refereeRegestrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refereeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRefereeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRefereeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refereeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(dateOfBirthTf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schoolIdTf, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NationalId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNationalId, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refereePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRefereePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refereeEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextRefereeEmailAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMale, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jRadioButtonFemale))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginRefereeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerBeginRefereeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSchoolTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areYouWillingToReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonYesWilling)
                    .addComponent(jRadioButtonNotWilling))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degreeToReferee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juvenileGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxYesJuvenile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minorGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxYesMinor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seniorGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxYesSeniorGrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(availabilityForSecondLevelGames, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAllTimeAvailableSecondLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxWeekdayAvailableSecondLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxWeekendAvailableSecondLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelRefereeRegestration, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButtonDoneRegesteringReferee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRefereeFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRefereeFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRefereeFirstNameActionPerformed

    private void jTextRefereePhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRefereePhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRefereePhoneNumberActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jComboBoxSchoolTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSchoolTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSchoolTeamActionPerformed

    private void jCheckBoxYesJuvenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxYesJuvenileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxYesJuvenileActionPerformed

    private void jButtonDoneRegesteringRefereeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneRegesteringRefereeActionPerformed
        // TODO add your handling code here:
        String fName = jTextRefereeFirstName.getText();
        String lName = jTextRefereeLastName.getText();
        java.sql.Date dateOfBirth = null;
        try{
            final DateFormat format = new SimpleDateFormat("dd/mm/yy");
            java.util.Date date = format.parse(dateOfBirthTf.getText()); 
            dateOfBirth = new java.sql.Date(date.getTime());
        }catch (ParseException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog (this, "Please input date of birth correctly");
            return;
        }
        int schoolId = Integer.parseInt(schoolIdTf.getText()+"");
        int nationalId = Integer.parseInt(jTextFieldNationalId.getText());
        int phoneNumber = Integer.parseInt(jTextRefereePhoneNumber.getText());
        String emailAddress = jTextRefereeEmailAddress.getText();
        String sex;
        if(jRadioButtonMale.isSelected()){
            sex = "male";
        }else{
            sex = "female";
        }
        int yearBeganReferee = Integer.parseInt(jSpinnerBeginRefereeYear.getValue().toString());
        String schoolTeam = jComboBoxSchoolTeam.getSelectedItem().toString();
        String willingInterCountyGames;
        if(jRadioButtonYesWilling.isSelected()){
            willingInterCountyGames = "Yes";
        }else{
            willingInterCountyGames = "No";
        }
        String refereeGrade;
        if(jCheckBoxYesJuvenile.isSelected()){
            refereeGrade = "Juvenile";
        }else if(jCheckBoxYesMinor.isSelected()){
            refereeGrade = "Minor";
        }else{
            refereeGrade = "Senior";
        }
        String availableSecondLevel;
        if(jCheckBoxAllTimeAvailableSecondLevel.isSelected()){
            availableSecondLevel = "All Time";
        }else if(jCheckBoxWeekdayAvailableSecondLevel.isSelected()){
            availableSecondLevel = "Week-days";
        }else{
            availableSecondLevel = "Weekends";
        }
        
        
         Common.CURRENT_REFEREE = new Referee(0,fName,lName ,dateOfBirth, schoolId, nationalId,phoneNumber,emailAddress,sex,yearBeganReferee,schoolTeam,willingInterCountyGames,refereeGrade,availableSecondLevel);
        
        
        setVisible(false);
        KabumbuFootballLeage.rrfc.populate();
        KabumbuFootballLeage.rrfc.setVisible(true);
        
    }//GEN-LAST:event_jButtonDoneRegesteringRefereeActionPerformed

    private void jButtonCancelRefereeRegestrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelRefereeRegestrationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KabumbuFootballLeage.rrhp.setVisible(true);
    }//GEN-LAST:event_jButtonCancelRefereeRegestrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RefereeRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RefereeRegestration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NationalId;
    private javax.swing.JLabel areYouWillingToReferee;
    private javax.swing.JLabel availabilityForSecondLevelGames;
    private javax.swing.JLabel beginReferee;
    private javax.swing.JLabel beginRefereeYear;
    private javax.swing.ButtonGroup buttonGroupFemaleOrMale;
    private javax.swing.ButtonGroup buttonGroupSecondLevel;
    private javax.swing.ButtonGroup buttonGroupYesOrNo;
    private javax.swing.ButtonGroup buttonGroupYesOrNoJuvenile;
    private javax.swing.ButtonGroup buttonGroupYesOrNoMinor;
    private javax.swing.ButtonGroup buttonGroupYesOrNoSeniorGrade;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField dateOfBirthTf;
    private javax.swing.JLabel degreeToReferee;
    private javax.swing.JButton jButtonCancelRefereeRegestration;
    private javax.swing.JButton jButtonDoneRegesteringReferee;
    private javax.swing.JCheckBox jCheckBoxAllTimeAvailableSecondLevel;
    private javax.swing.JCheckBox jCheckBoxWeekdayAvailableSecondLevel;
    private javax.swing.JCheckBox jCheckBoxWeekendAvailableSecondLevel;
    private javax.swing.JCheckBox jCheckBoxYesJuvenile;
    private javax.swing.JCheckBox jCheckBoxYesMinor;
    private javax.swing.JCheckBox jCheckBoxYesSeniorGrade;
    private javax.swing.JComboBox<String> jComboBoxSchoolTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonNotWilling;
    private javax.swing.JRadioButton jRadioButtonYesWilling;
    private javax.swing.JSpinner jSpinnerBeginRefereeYear;
    private javax.swing.JTextField jTextFieldNationalId;
    private javax.swing.JTextField jTextRefereeEmailAddress;
    private javax.swing.JTextField jTextRefereeFirstName;
    private javax.swing.JTextField jTextRefereeLastName;
    private javax.swing.JTextField jTextRefereePhoneNumber;
    private javax.swing.JLabel juvenileGrade;
    private javax.swing.JLabel minorGrade;
    private javax.swing.JLabel refereeEmailAddress;
    private javax.swing.JLabel refereeFirstName;
    private javax.swing.JLabel refereeLastName;
    private javax.swing.JLabel refereePhoneNumber;
    private javax.swing.JLabel refereeRegestrationForm;
    private javax.swing.JTextField schoolIdTf;
    private javax.swing.JLabel schoolTeam;
    private javax.swing.JLabel seniorGrade;
    private javax.swing.JLabel sex;
    // End of variables declaration//GEN-END:variables
}
